# Generated by Django 6.1.1 on 2026-09-29 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_burn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('runway_months', models.DecimalField(decimal_places=1, default=12.0, max_digits=5)),
                ('active_projects_count', models.IntegerField(default=0)),
                ('pending_approvals_count', models.IntegerField(default=0)),
                ('headcount', models.IntegerField(default=0)),
                ('delay_risk_score', models.IntegerField(default=15)),
                ('ai_narrative', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
