# Generated by Django 6.1.1 on 2026-09-29 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('LEAVE_REQUESTED', 'Employee Leave Requested'), ('INVOICE_CREATED', 'New Invoice Created'), ('EXPENSE_SUBMITTED', 'Expense Submitted'), ('DOCUMENT_UPLOADED', 'New Document Uploaded'), ('TASK_OVERDUE', 'Task Overdue'), ('EMPLOYEE_JOINED', 'New Employee Onboarded'), ('MANUAL', 'Manual Trigger')], default='MANUAL', max_length=50)),
                ('conditions_json', models.JSONField(blank=True, default=dict)),
                ('actions_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING_APPROVAL', 'Pending Approval'), ('RUNNING', 'Running')], default='SUCCESS', max_length=30)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('log_output', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('module', models.CharField(default='General', max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approvals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='companies.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
                ('workflow_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
