import uuid
from django.db import models
from django.conf import settings
from apps.companies.models import Company

class Workflow(models.Model):
    """Visual multi-step trigger-condition-action workflow engine."""

    TRIGGER_CHOICES = (
        ('LEAVE_REQUESTED', 'Employee Leave Requested'),
        ('INVOICE_CREATED', 'New Invoice Created'),
        ('EXPENSE_SUBMITTED', 'Expense Submitted'),
        ('DOCUMENT_UPLOADED', 'New Document Uploaded'),
        ('TASK_OVERDUE', 'Task Overdue'),
        ('EMPLOYEE_JOINED', 'New Employee Onboarded'),
        ('MANUAL', 'Manual Trigger'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='workflows')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    trigger_type = models.CharField(max_length=50, choices=TRIGGER_CHOICES, default='MANUAL')
    conditions_json = models.JSONField(default=dict, blank=True)
    actions_json = models.JSONField(default=dict, blank=True)
    is_active = models.BooleanField(default=True)
    execution_count = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} ({self.trigger_type})"


class WorkflowExecution(models.Model):
    """Execution history of a workflow."""

    STATUS_CHOICES = (
        ('SUCCESS', 'Success'),
        ('FAILED', 'Failed'),
        ('PENDING_APPROVAL', 'Pending Approval'),
        ('RUNNING', 'Running'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workflow = models.ForeignKey(Workflow, on_delete=models.CASCADE, related_name='executions')
    triggered_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='SUCCESS')
    context_data = models.JSONField(default=dict, blank=True)
    log_output = models.TextField(blank=True)
    executed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-executed_at']


class ApprovalRequest(models.Model):
    """1-Click Approval queue item generated by workflows."""

    STATUS_CHOICES = (
        ('PENDING', 'Pending Approval'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='approval_requests')
    workflow_execution = models.ForeignKey(WorkflowExecution, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=255)
    module = models.CharField(max_length=50, default='General')
    entity_id = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    requested_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='submitted_approvals')
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_approvals')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    reviewer_comment = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
