# Generated by Django 6.1.1 on 2026-09-29 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_entity', models.CharField(choices=[('EMPLOYEE', 'Employee Record'), ('TASK', 'Task Item'), ('INVOICE', 'Invoice'), ('DOCUMENT', 'Document'), ('PROJECT', 'Project')], max_length=30)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('TEXT', 'Short Text'), ('NUMBER', 'Number'), ('DATE', 'Date Picker'), ('DROPDOWN', 'Dropdown Select'), ('BOOLEAN', 'Toggle / Checkbox')], default='TEXT', max_length=30)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=255)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='customization.customfield')),
            ],
            options={
                'unique_together': {('custom_field', 'entity_id')},
            },
        ),
    ]
